#!/bin/bash
#
# (C) Copyright IBM Corporation 2018, 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM adoptopenjdk/maven-openjdk8-openj9:latest as mvnbuild-openj9

RUN apt-get update \
    && apt-get install -y --no-install-recommends git vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/src

ARG app_repo=dinogun
ARG app_name=watson-springboot

RUN git clone https://github.com/${app_repo}/${app_name}.git

WORKDIR /opt/src/${app_name}

RUN mvn -f pom-java-v8.xml install dependency:copy-dependencies

RUN mvn -f pom-java-v8.xml clean package

FROM adoptopenjdk/openjdk8-openj9:alpine-slim

WORKDIR /opt/app

RUN adduser -u 1001 -S -G root -s /usr/sbin/nologin default \
    && chown -R 1001:0 /opt/app \
    && chmod -R g+rw /opt/app

USER 1001

COPY --chown=1001:0 --from=mvnbuild-openj9 /opt/src/watson-springboot/ /opt/app/

CMD ["sh","target/bin/webapp"]
