#!/bin/bash
#
# (C) Copyright IBM Corporation 2018, 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM adoptopenjdk/maven-openjdk11-openj9:latest as mvnbuild-jdk11-openj9-slim

RUN rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/src

ARG app_repo=dinogun
ARG app_name=watson-springboot

RUN git clone https://github.com/${app_repo}/${app_name}.git \
    && cd ${app_name} \
    && mvn -e -B -f pom-java-v11.xml dependency:resolve

RUN cd ${app_name} \
    && mvn -f pom-java-v11.xml package

FROM adoptopenjdk/openjdk11-openj9:alpine-slim

WORKDIR /opt/app

COPY --from=mvnbuild-jdk11-openj9-slim /opt/src/watson-springboot/ /opt/app/

CMD ["sh","target/bin/webapp"]
